name: Linter check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install devtools
      run: make devtools
      
    - name: Run Linter
      run: make check
